---
title: "Data Import"
output: html_document
---


```{r setup, echo = FALSE, message  = FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

## Import the FAS litters CSV

```{r}
litters_df = read_csv("data_import_examples/FAS_Litters.csv")

#remove blank space and set letters to lower_case to overwrite the previous version
litters_df = janitor::clean_names(litters_df)

head(litters_df)
tail(litters_df)
```
```{r eval = FALSE}
view(litters_df)
```


```{r}
pups_df = read_csv("data_import_examples/FAS_pups.csv")

pups_df = janitor::clean_names(pups_df)
```

Use absolute path

```{r, eval = FALSE}
pups_df = read_csv("/Users/lixueting/Desktop/哥大/8105/data_wrangling/data_import_examples/FAS_pups.csv")
```

## Look at read_csv options

```{r}
litters_df = read.csv(
  file = "data_import_examples/FAS_litters.csv",
  skip = 0 ## number of lines you need to skip
)
```

What about missing data

```{r}
litters_df = read.csv(
  file = "data_import_examples/FAS_litters.csv",
  na = c("NA", "", ".") ## convert all weired things to NA value
)

litters_df = janitor::clean_names(litters_df)

pull(litters_df, gd0_weight)

```

What if we code `group` as a factor variable?

```{r}
litters_df = read_csv(
  file = "data_import_examples/FAS_litters.csv",
  na = c("NA", "", "."),
  col_types = cols(
    Group = col_factor()
  )
)
```

## Import an excel file

Import MLB 2011 summary data.

```{r}
#range command can choose specific columns
mlb_df = read_excel("data_import_examples/mlb11.xlsx", sheet = "mlb11")

```

## Import SAS data

```{r}
pulse_df = read_sas("data_import_examples/public_pulse_data.sas7bdat")
```

## Never use read.csv(), read_csv() can offer a tibble format dataframe
## Never use $ to select and manipulate columns from a dataset









